version: "3.8"
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: notesadmin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notesapi
    ports:
      - '5432:5432'
    volumes:
      - ./scripts/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      - db:/var/lib/postgresql/data

  notes-app:
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - '4000:4000'
    environment:
      DB_HOST: postgres
      PORT: 4000
    volumes:
      - ./notes:/opt/notes-app/notes
      - ./public:/opt/notes-app/public
      - ./scripts:/opt/notes-app/scripts
      - ./server:/opt/notes-app/server
      - ./src:/opt/notes-app/src
      - ./credentials.js:/opt/notes-app/credentials.js

  server:
    build:
      context: ./rails/
      dockerfile: Dockerfile
    depends_on:
      - postgres
    command: ./bin/server
    volumes:
      - ./rails:/app
    ports:
      - "3000:3000"
      - "3035:3035"

volumes:
  db:
